// ============================================================
// STATE
// ============================================================
export const state = {
  algo: 'brute',
  running: false,
  paused: false,
  stepMode: false,
  stepResolve: null,
  animSpd: 1,
  startTime: 0,
  bestPath: [],
  curPath: [],
  nodeStates: {},
  rejEdges: [],
  orbs: [],
  graphSc: 1,
  graphOx: 0,
  graphOy: 0,
  isDrag: false,
  lastMX: { x: 0, y: 0 },
  dragCity: null,
  costHistory: [],
  dpData: {},
  stackFrames: [],
  treeNodes: [],
  treeEdges: [],
  treeStep: 0,
  totalPerms: 0,
  donePerms: 0,
  S: { nodes: 0, calls: 0, best: Infinity, cur: 0, tours: 0, steps: 0, time: 0, depth: 0 },
  cityPos: {},
  treeZoom: 1.0,
  lastT: 0,
};
